### ISSUE TITLE
Unsupported widget

### ISSUE THREAD

**Issue by rahra** [heqro/colorschemeswapper-plasmoid#10]
I just installed it on KDE 6.6.0 (qt 6.6.2) and cannot add it to the panel because it appears as "unsupported widget".

**Comment by Goldaracena** [comment]
Thank you for reporting this.

Could you please confirm you have not mistakenly installed the Plasma 5 version? I enclose a screenshot of Pling with the details of the version that _should_ work with Plasma 6. 

![Screenshot_20241218_112618](https://github.com/user-attachments/assets/382f6750-e914-48bd-ac48-91b1561aae07)

**Comment by rahra** [comment]
I installed it from the KDE store. I will check what version was installed, stand by.

**Comment by rahra** [comment]
I had a look into `~/.local/share/plasma/plasmoids` and the manifest showed that the old version was installed.
But how do I install the new one?

**Comment by Goldaracena** [comment]
The way to go is to uninstall it first, then to install the correct version via "add new widgets...". Trying to install the widget will yield a list of two download options - pick the most recent one.

18 Dec 2024 19:25:25 Bernhard R. Fischer ***@***.***>:

**Comment by rahra** [comment]
Ok, sorry for bothering you. I didn't see the selection at first - stupid me.
Now it works!
Thanks for this useful plugin!

**Comment by Goldaracena** [comment]
My pleasure. Enjoy!

**Comment by rahra** [comment]
BTW: The widget switches between "Breeze Dark" and "Breeze Classic" by default.
On modern Kubuntu versions (24.10 and 24.04) there is "Breeze Dark" and "Breeze", the latter being the default. So, while switching to "Breeze classic" is possible, it looks slightly different than the default Breeze.
I changed the setting in the widget settings from "Breeze classic" to Breeze.
