### ISSUE TITLE
Port to KF6/Plasma6 

### ISSUE THREAD

**Issue by ashwinvis** [heqro/colorschemeswapper-plasmoid#4]
First of all, thanks! It used to work in KDE Neon with Plasma 5 as expected for me.

The plasmoid needs to be ported for use in Plasma 6. I found this guide in the docs:
https://develop.kde.org/docs/plasma/widget/porting_kf6/

**Comment by Goldaracena** [comment]
Thank you for using the widget.
I'm very busy with university matters this year. Do you know of any quick way to let the end user know that the widget does not support Plasma 6 (yet)?

**Comment by ashwinvis** [comment]
Plasma 6 detects itself that the widget is incompatible. No intervention necessary.

**Comment by Adashi12** [comment]
I used this plasmoid a lot and am looking forward to use it again on Plasma 6!

**Comment by ashwinvis** [comment]
@heqro I can give it a try.

**Comment by Goldaracena** [comment]
Actually, I'm about to push the update to Plasma 6 to this repo. I can ping you guys once it's done.

**Comment by Goldaracena** [comment]
@Adashi12 @ashwinvis If you know how to install plasmoids from Github, could you check if this plasmoid is already working for you?

**Comment by ashwinvis** [comment]
@heqro I cloned and copied over the package directory to `~/.local/share/plasma/plasmoids`. If I execute `plasmoidviewer -a . `  inside the directory, it works in a test window, with some warnings

![image](https://github.com/heqro/colorschemeswapper-plasmoid/assets/9155111/84f51ede-bdb6-4483-890c-f5d4a0d20643)

```
❯ plasmoidviewer -a .
QML debugging is enabled. Only use this in a safe environment.
qml: View QML loaded
kf.plasma.quick: Applet preload policy set to 1
file:///usr/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/main.qml:196:25: QML FolderViewDropArea (parent or ancestor of QQuickLayoutAttached): Binding loop detected for property "minimumWidth"
Toolbox not loading, toolbox package is either invalid or disabled.
qml: New Containment: ContainmentItem_QML_45(0x63f0f48d8060, "desktop")
qt.qml.context: file:///home/avmo/.local/share/plasma/plasmoids/colorschemeswapper-plasmoid/package/contents/ui/main.qml:34:9 Parameter "sourceName" is not declared. Injection of parameters into signal handlers is deprecated. Use JavaScript functions with formal parameters instead.
```


However if I add it to a real panel, I get this

![image](https://github.com/heqro/colorschemeswapper-plasmoid/assets/9155111/8e47adc8-1fa3-4f5d-a30d-21540ea22879)

The icon is broken and does not work as it should.

**Comment by Goldaracena** [comment]
May I ask you if, after installation, you restarted your system? I have personally found that, after logging in and out, it started working properly. As you may know, `plasmoidviewer -a` does "update" the widget inside the test window you show, but it actually does not update the widget for your system.

Consequently, I think that you may be running the older version of the widget.

Finally, provided it works on your end after solving this issue, I may ship this to the KDE Store and then try to work out the Warnings on free time/code contributions from people who may want to give a hand.

**Comment by ashwinvis** [comment]
I had removed the old plasmoid. I verified this by removing the development version and the plasmoid no longer appears in the "Add widgets" box. I have tried logging out and even restarting, the issue persisted.

Finally, I fixed the metadata (see the PR above) since it contained some Plasma 5 items.

**Comment by Goldaracena** [comment]
Thank you for that! I have already merged the PR. If it works now on your end, I'll upload to KDE Store in the coming moments.
