### ISSUE TITLE
Changing Icon B actually changes Icon A

### ISSUE THREAD

**Issue by odinu** [heqro/colorschemeswapper-plasmoid#6]
Can't change Icon B - the choice I select actually gets applied to Icon A instead.

**Comment by Goldaracena** [comment]
The latest batch of commits should have fixed it. I have not updated the changes to the KDE Store. If you happen to know how to update the widget from github, could you confirm this has been fixed on your end as well? 

Otherwise I can just upload to the KDE Store and see what's up.

**Comment by Ubiquitine** [comment]
I can confirm that updating applet from git code fixed the issue with icon B.

**Comment by Goldaracena** [comment]
Thank you. Closing.
