### ISSUE TITLE
Change Konsole profile, too

### ISSUE THREAD

**Issue by Lex-2008** [heqro/colorschemeswapper-plasmoid#7]
First, thanks for the nice little widget! Make my days brighter and nights... well, darker, I guess? :)

Second, I noticed that while Konsole follows the system theme _in UI_ (menu and tab bar, Window decorations), it unfortunately keeps using existing profile (which includes color scheme for actual terminal contents).

However, someone recently [published this little script][x] which not only updates default settings, but also walks through all open Konsole services/windows/sessions and changes profile in them! Nice!

I wonder if you would like to have something like this integrated into this plasmoid?

[x]: https://discuss.kde.org/t/how-do-i-make-konsole-follow-system-theme/933/10

**Comment by Goldaracena** [comment]
Hi,

Thank you for your interest in the improvement of the plasmoid! 

As it stands now, I am not able to add more functionality. I don't find myself using Plasma on my development rig*. However, I would not oppose to merge any pull request attempting to tackle this problem.

Regardless, the proposed solution looks a bit hacky. It requires, for instance, to know the profile name you want to swap to beforehand. Furthermore, I struggle to devise a nice enough UI solution that does not look off for this new functionality w.r.t. the previous one. Nevertheless, we can leave this thread open and see if someone wants to chime in.

*This comment does _not_ imply that the widget is not maintained - I think the functionality set that I attempted to tackle is covered, hence no new updates have come out as of lately. I'd get around to solving regressions.

**Comment by Lex-2008** [comment]
Thanks for the prompt answer, @heqro!

Regarding UI solution - I was thinking about adding few controls to the config page: a checkbox "Also switch Konsole profiles" with two ComboBoxes listing available profiles.

And it's possible to get a list of available profiles by running `konsole --list-profiles`. It only doesn't list the profile called "Built-in", but then I'm not sure how to activate it, either.

But I totally not insist on you making this change :) I implemented this a hacky way for myself, and I can make it a "proper" way (with configuration options exposed in UI) after we agree how the options page should look and if there are more people who would like to have this feature.

On the other hand I totally agree that it almost doubles amount of options so maybe turns a "nice little widget" into not-so little?... So maybe a single text field "run this command on color scheme change" would be enough, to potentially avoid people asking for more options: changing also wallpapers, cursors, themes in other applications, etc...

**Comment by Goldaracena** [comment]
I have finally settled for the last of your options. I have just pushed the change to GitHub and I'm meaning to push it to the widgets download page in a minute.

**Comment by Lex-2008** [comment]
Works great! Thank you very much!
